# Generated by Django 5.1.5 on 2025-01-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.CharField(choices=[('first', 'First Year'), ('second', 'Second Year'), ('third', 'Third Year'), ('fourth', 'Fourth Year')], max_length=10)),
            ],
        ),
    ]
